CREATE TABLE BOOKS
(
    ID     INT PRIMARY KEY AUTO_INCREMENT,
    TITLE  VARCHAR(255),
    AUTHOR INT,
    GENRE  INT
);
CREATE TABLE AUTHORS
(
    ID   INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255)
);
CREATE TABLE GENRES
(
    ID   INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255)
);
CREATE TABLE COMMENTS
(
    ID        INT PRIMARY KEY AUTO_INCREMENT,
    NICK_NAME VARCHAR(255),
    BODY      VARCHAR(255),
    BOOK_ID   VARCHAR(255)
);
CREATE TABLE USERS
(
    USER_ID       INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    ENABLED  BOOLEAN NOT NULL
);
CREATE TABLE ROLES
(
    ROLE_ID   INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL
);
CREATE TABLE USERS_ROLES
(
    USER_ID INT NOT NULL,
    ROLE_ID INT NOT NULL
);